### PR TITLE
No longer use snekfetch

### PR DESCRIPTION
**Pull request by sufficients**

### CODE REVIEW

**Review by c-harlotte — CHANGES_REQUESTED** [review]
why did u use r2 use axios dujmb fukc!!!!!!!!!

**Comment by sufficients** [comment]
ok

**Comment by c-harlotte** [comment]
Thanks

**Comment by sufficients** [comment]
Done

**Comment by c-harlotte** [comment]
Thnaks

**Review by c-harlotte — APPROVED** [review]
Yes

**Pull request merged**
